### ISSUE TITLE
Consider moving sauce labs integration to another library

### ISSUE THREAD

**Issue by thedeeno** [jlipps/yiewd#16]
This project looks awesome! When looking at the code base I was surprised to see saucelabs so closely coupled. For companies that don't use sauce labs this adds conceptual weight to the yiewd dependency for a seemingly needless reason.

Perhaps extract and call out the extension In the readme?

**Comment by jlipps** [comment]
That's a good idea; I might be able to get around to it soon. FWIW I've stopped using yiewd personally and instead am using wd's promiseChainRemote in conjunction with [async/await](http://jakearchibald.com/2014/es7-async-functions/). Since I use a transpiler anyway, this eliminates the need for both yiewd and monocle-js, and (I think) makes the code cleaner.

**Comment by thedeeno** [comment]
Ooo, I thought it was to early for that. What transpiler are you using? If you have a chance can you give me a sentence or two on the pipeline? I'd love to move that way if possible as well (I can even help build the workflow out :))

**Comment by jlipps** [comment]
I use babel. I have another project (https://github.com/jlipps/runsauce) that uses babel, es6, and wd.js (wd code is in tests.js, have a look)

**Comment by vvo** [comment]
Should we edit the README to say "deprecated, use wd + async/await"?

**Comment by jlipps** [comment]
Yes, will do.
